// Mocks generated by Mockito 5.4.6
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:aguka_mobile/core/error/failures.dart' as _i6;
import 'package:aguka_mobile/core/usecases/usecase.dart' as _i10;
import 'package:aguka_mobile/features/auth/domain/entities/user_entity.dart'
    as _i7;
import 'package:aguka_mobile/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:aguka_mobile/features/auth/domain/usecases/check_auth_status_usecase.dart'
    as _i12;
import 'package:aguka_mobile/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i11;
import 'package:aguka_mobile/features/auth/domain/usecases/login_usecase.dart'
    as _i4;
import 'package:aguka_mobile/features/auth/domain/usecases/logout_usecase.dart'
    as _i9;
import 'package:aguka_mobile/features/auth/domain/usecases/onboarding_usecase.dart'
    as _i13;
import 'package:aguka_mobile/features/auth/domain/usecases/register_usecase.dart'
    as _i8;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginUseCase].
class MockLoginUseCase extends _i1.Mock implements _i4.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> call(
          _i4.LoginParams? params) =>
      (super.noSuchMethod(
        Invocation.method(#call, [params]),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#call, [params]),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);
}

/// A class which mocks [RegisterUseCase].
class MockRegisterUseCase extends _i1.Mock implements _i8.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> call(
          _i8.RegisterParams? params) =>
      (super.noSuchMethod(
        Invocation.method(#call, [params]),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#call, [params]),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);
}

/// A class which mocks [LogoutUseCase].
class MockLogoutUseCase extends _i1.Mock implements _i9.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i10.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(#call, [params]),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, void>>.value(
                _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(#call, [params]),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetCurrentUserUseCase].
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i11.GetCurrentUserUseCase {
  MockGetCurrentUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> call(
          _i10.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(#call, [params]),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#call, [params]),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);
}

/// A class which mocks [CheckAuthStatusUseCase].
class MockCheckAuthStatusUseCase extends _i1.Mock
    implements _i12.CheckAuthStatusUseCase {
  MockCheckAuthStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i5.Future<bool> call() => (super.noSuchMethod(
        Invocation.method(#call, []),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [OnboardingUseCase].
class MockOnboardingUseCase extends _i1.Mock
    implements _i13.OnboardingUseCase {
  MockOnboardingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> call(
          _i13.OnboardingParams? params) =>
      (super.noSuchMethod(
        Invocation.method(#call, [params]),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#call, [params]),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);
}

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> login({
    required String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#login, [], {
          #phone: phone,
          #password: password,
        }),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#login, [], {
            #phone: phone,
            #password: password,
          }),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> register({
    required String? phone,
    required String? password,
    required String? fullName,
    required String? role,
    String? email,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#register, [], {
          #phone: phone,
          #password: password,
          #fullName: fullName,
          #role: role,
          #email: email,
          #language: language,
        }),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#register, [], {
            #phone: phone,
            #password: password,
            #fullName: fullName,
            #role: role,
            #email: email,
            #language: language,
          }),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> onboardFarmer(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(#onboardFarmer, [data]),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#onboardFarmer, [data]),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> onboardOfficer(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(#onboardOfficer, [data]),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#onboardOfficer, [data]),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> onboardCooperative(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(#onboardCooperative, [data]),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#onboardCooperative, [data]),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> logout() =>
      (super.noSuchMethod(
        Invocation.method(#logout, []),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(#logout, []),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(#getCurrentUser, []),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#getCurrentUser, []),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> getProfile() =>
      (super.noSuchMethod(
        Invocation.method(#getProfile, []),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#getProfile, []),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> updateProfile({
    required String? firstName,
    required String? lastName,
    required String? district,
    required String? sector,
    required String? cell,
    required String? village,
    String? farmSize,
    String? primaryCrop,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#updateProfile, [], {
          #firstName: firstName,
          #lastName: lastName,
          #district: district,
          #sector: sector,
          #cell: cell,
          #village: village,
          #farmSize: farmSize,
          #primaryCrop: primaryCrop,
        }),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(#updateProfile, [], {
            #firstName: firstName,
            #lastName: lastName,
            #district: district,
            #sector: sector,
            #cell: cell,
            #village: village,
            #farmSize: farmSize,
            #primaryCrop: primaryCrop,
          }),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i5.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(#isAuthenticated, []),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> refreshToken() =>
      (super.noSuchMethod(
        Invocation.method(#refreshToken, []),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(#refreshToken, []),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> clearLocalSession() =>
      (super.noSuchMethod(
        Invocation.method(#clearLocalSession, []),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(#clearLocalSession, []),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
