// Mocks generated by Mockito 5.4.6 from annotations
// in aguka_mobile/test/unit/reports/reports_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aguka_mobile/core/error/failures.dart' as _i5;
import 'package:aguka_mobile/features/reports/domain/entities/report_entity.dart'
    as _i6;
import 'package:aguka_mobile/features/reports/domain/repositories/reports_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReportsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportsRepository extends _i1.Mock implements _i3.ReportsRepository {
  MockReportsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ReportAnalyticsEntity>>
      getAnalytics() => (super.noSuchMethod(
            Invocation.method(
              #getAnalytics,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i6.ReportAnalyticsEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.ReportAnalyticsEntity>(
              this,
              Invocation.method(
                #getAnalytics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ReportAnalyticsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> downloadReport(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadReport,
          [type],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #downloadReport,
            [type],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);
}
