import PDFDocument from "pdfkit";
import ExcelJS from "exceljs";
import { Response } from "express";

import {
  BrandingMetadata,
  reportBrandingService,
} from "../services/report-branding.service.js";

export const convertToCSV = (data: any[], meta?: BrandingMetadata): string => {
  if (!data || data.length === 0) return "";

  const headerRows = meta
    ? [
        `AGUKA SMART FARMING KIT`,
        `Report: ${meta.reportTitle}`,
        `Generated By: ${meta.generatedBy || "System"} (${meta.userRole || "N/A"})`,
        `Date: ${reportBrandingService.formatDate(meta.generatedAt)}`,
        ``,
      ].map((line) => `"${line.replace(/"/g, '""')}"`)
    : [];

  const headers = Object.keys(data[0]);
  const csvRows = data.map((row) =>
    headers
      .map((fieldName) => {
        let value = row[fieldName];
        if (value === null || value === undefined) value = "";
        if (typeof value === "object") value = JSON.stringify(value);
        return JSON.stringify(String(value));
      })
      .join(","),
  );

  return [...headerRows, headers.join(","), ...csvRows].join("\n");
};

export const generateExcelReport = async (
  res: Response,
  filename: string,
  sheets: { name: string; data: any[] }[],
) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "AGUKA SMART FARMING KIT";

  for (const sheet of sheets) {
    const worksheet = workbook.addWorksheet(sheet.name);
    if (sheet.data && sheet.data.length > 0) {
      const headers = Object.keys(sheet.data[0]);
      worksheet.columns = headers.map((h) => ({
        header: h,
        key: h,
        width: 20,
      }));
      worksheet.addRows(sheet.data);
    }
  }

  res.setHeader(
    "Content-Type",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  );
  res.setHeader("Content-Disposition", `attachment; filename=${filename}.xlsx`);

  await workbook.xlsx.write(res);
  res.end();
};

export const generatePDFReport = (
  res: Response,
  title: string,
  summaryText: string,
  tables: { title: string; headers: string[]; rows: string[][] }[],
  hash?: string,
) => {
  const doc = new PDFDocument({ margin: 50 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${title.replace(/ /g, "_")}.pdf`,
  );
  doc.pipe(res);

  // Title
  doc.fontSize(20).text(title, { align: "center" });
  doc.moveDown();

  // Timestamp
  doc
    .fontSize(10)
    .text(`Generated: ${new Date().toISOString()}`, { align: "right" });
  if (hash) {
    doc.text(`Hash: ${hash}`, { align: "right" });
  }
  doc.moveDown(2);

  // Summary
  doc.fontSize(14).text("Summary", { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(12).text(summaryText);
  doc.moveDown(2);

  // Tables
  for (const table of tables) {
    doc.fontSize(14).text(table.title, { underline: true });
    doc.moveDown(0.5);

    // Draw headers
    let y = doc.y;
    doc.fontSize(10).font("Helvetica-Bold");
    let xOffset = 50;
    const colWidth = (doc.page.width - 100) / table.headers.length;

    for (const header of table.headers) {
      doc.text(header, xOffset, y, { width: colWidth });
      xOffset += colWidth;
    }
    doc.moveDown(0.5);
    y = doc.y;
    doc.font("Helvetica");

    // Draw rows
    for (const row of table.rows) {
      xOffset = 50;
      for (const cell of row) {
        doc.text(cell, xOffset, y, { width: colWidth });
        xOffset += colWidth;
      }
      y += 15;
      if (y > doc.page.height - 100) {
        doc.addPage();
        y = 50;
      }
    }
    doc.y = y + 20;
  }

  doc.end();
};
