export interface FinancialReportFilters {
  startDate: Date;
  endDate: Date;
  cooperativeId?: string;
}

export interface FinancialReportContent {
  summary: {
    totalRevenue: number;
    totalRefunds: number;
    netRevenue: number;
    transactionCount: number;
  };
  payments: Array<{
    id: string;
    amount: number;
    currency: string;
    provider: string;
    paymentType: string;
    status: string;
    phoneNumber: string;
    createdAt: Date;
    user?: { id: string; phone: string; fullName?: string | null };
  }>;
  refunds: Array<{
    id: string;
    amount: number;
    reason: string;
    status: string;
    createdAt: Date;
    paymentId: string;
  }>;
}

import {
  BrandingMetadata,
  reportBrandingService,
} from "./report-branding.service.js";

export class ReportCsvEngine {
  escapeCsvField(value: unknown): string {
    if (value === null || value === undefined) return "";
    const str = String(value);
    if (
      str.includes(",") ||
      str.includes('"') ||
      str.includes("\n") ||
      str.includes("\r")
    ) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  }

  exportFinancialReportCSV(
    content: FinancialReportContent,
    reportId: string,
    meta?: BrandingMetadata,
  ) {
    const headerRows = [
      `AGUKA SMART FARMING KIT`,
      `Report: ${meta?.reportTitle || "Financial Report"}`,
      `Generated By: ${meta?.generatedBy || "System"} (${meta?.userRole || "N/A"})`,
      `Date: ${reportBrandingService.formatDate(meta?.generatedAt || new Date())}`,
      `ID: ${reportId}`,
      ``, // Empty line before data
    ].map((line) => this.escapeCsvField(line));

    const dataLines = [
      "id,type,amount,currency,status,provider,phone,createdAt,reason",
      ...content.payments.map((payment) =>
        [
          this.escapeCsvField(payment.id),
          "payment",
          this.escapeCsvField(payment.amount),
          this.escapeCsvField(payment.currency),
          this.escapeCsvField(payment.status),
          this.escapeCsvField(payment.provider),
          this.escapeCsvField(payment.phoneNumber),
          this.escapeCsvField(payment.createdAt),
          "",
        ].join(","),
      ),
      ...content.refunds.map((refund) =>
        [
          this.escapeCsvField(refund.id),
          "refund",
          this.escapeCsvField(refund.amount),
          "RWF",
          this.escapeCsvField(refund.status),
          "",
          "",
          this.escapeCsvField(refund.createdAt),
          this.escapeCsvField(refund.reason),
        ].join(","),
      ),
    ];

    const allLines = [...headerRows, ...dataLines];

    return {
      buffer: Buffer.from(allLines.join("\n"), "utf-8"),
      contentType: "text/csv",
      filename: `financial-report-${reportId.slice(0, 8)}.csv`,
    };
  }
}

export const reportCsvEngine = new ReportCsvEngine();
