import ExcelJS from "exceljs";
import {
  reportBrandingService,
  BrandingMetadata,
} from "./report-branding.service.js";

export interface ExcelSheetData {
  name: string;
  headers: string[];
  rows: any[][];
}

export class ReportExcelEngine {
  async generateBrandedExcel(
    sheets: ExcelSheetData[],
    meta: BrandingMetadata,
  ): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = "AGUKA SMART FARMING KIT";
    workbook.lastModifiedBy = meta.generatedBy || "System";
    workbook.created = meta.generatedAt;

    for (const sheetData of sheets) {
      const worksheet = workbook.addWorksheet(sheetData.name);

      // 1. Add Branding Header
      // Row 1: System Name
      worksheet.mergeCells("A1:E1");
      const titleCell = worksheet.getCell("A1");
      titleCell.value = "AGUKA SMART FARMING KIT";
      titleCell.font = {
        name: "Arial",
        size: 16,
        bold: true,
        color: { argb: "FF1D9E75" },
      };
      titleCell.alignment = { vertical: "middle", horizontal: "left" };

      // Row 2: Subtitle
      worksheet.mergeCells("A2:E2");
      const subtitleCell = worksheet.getCell("A2");
      subtitleCell.value =
        "Smart Agriculture Monitoring & Decision Support System";
      subtitleCell.font = {
        name: "Arial",
        size: 10,
        italic: true,
        color: { argb: "FF6B7280" },
      };

      // Row 3: Report Title
      worksheet.mergeCells("A3:E3");
      const reportTitleCell = worksheet.getCell("A3");
      reportTitleCell.value = meta.reportTitle.toUpperCase();
      reportTitleCell.font = { name: "Arial", size: 12, bold: true };
      reportTitleCell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFF3F4F6" },
      };

      // Row 4: Metadata
      worksheet.getCell("A4").value = "Generated By:";
      worksheet.getCell("B4").value = meta.generatedBy || "System";
      worksheet.getCell("C4").value = "Role:";
      worksheet.getCell("D4").value = meta.userRole || "N/A";

      worksheet.getCell("A5").value = "Date:";
      worksheet.getCell("B5").value = reportBrandingService.formatDate(
        meta.generatedAt,
      );
      if (meta.season) {
        worksheet.getCell("C5").value = "Season:";
        worksheet.getCell("D5").value = meta.season;
      }

      // Add Logo (if possible - ExcelJS supports images but needs a lot of positioning math)
      try {
        const logoId = workbook.addImage({
          filename: reportBrandingService.getLogoPath(),
          extension: "png",
        });
        worksheet.addImage(logoId, {
          tl: { col: 5, row: 0 },
          ext: { width: 80, height: 80 },
        });
      } catch (e) {
        // Fallback if logo not found
      }

      // 2. Add Table Data (starting at row 7)
      const startRow = 7;
      const headerRow = worksheet.getRow(startRow);
      headerRow.values = sheetData.headers;
      headerRow.font = { bold: true, color: { argb: "FFFFFFFF" } };
      headerRow.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FF1D9E75" },
      };
      headerRow.alignment = { horizontal: "center" };

      // Add border to headers
      sheetData.headers.forEach((_, i) => {
        const cell = headerRow.getCell(i + 1);
        cell.border = {
          top: { style: "thin" },
          left: { style: "thin" },
          bottom: { style: "thin" },
          right: { style: "thin" },
        };
      });

      // Add Data Rows
      sheetData.rows.forEach((rowData, index) => {
        const row = worksheet.addRow(rowData);

        // Alternating row colors
        if (index % 2 !== 0) {
          row.fill = {
            type: "pattern",
            pattern: "solid",
            fgColor: { argb: "FFF9FAFB" },
          };
        }

        // Add borders to cells
        row.eachCell((cell) => {
          cell.border = {
            top: { style: "thin", color: { argb: "FFE5E7EB" } },
            left: { style: "thin", color: { argb: "FFE5E7EB" } },
            bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
            right: { style: "thin", color: { argb: "FFE5E7EB" } },
          };
          cell.alignment = { vertical: "middle" };
        });
      });

      // 3. Sheet Formatting
      worksheet.views = [{ state: "frozen", ySplit: startRow, xSplit: 0 }];
      worksheet.autoFilter = {
        from: { row: startRow, column: 1 },
        to: { row: startRow, column: sheetData.headers.length },
      };

      // Auto-width columns
      worksheet.columns.forEach((column) => {
        let maxColumnLength = 0;
        column.eachCell!({ includeEmpty: true }, (cell) => {
          const columnLength = cell.value ? cell.value.toString().length : 10;
          if (columnLength > maxColumnLength) {
            maxColumnLength = columnLength;
          }
        });
        column.width = maxColumnLength < 12 ? 12 : maxColumnLength + 2;
      });
    }

    return (await workbook.xlsx.writeBuffer()) as unknown as Buffer;
  }
}

export const reportExcelEngine = new ReportExcelEngine();
