import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface BrandingMetadata {
  reportTitle: string;
  userRole?: string;
  generatedBy?: string;
  generatedAt: Date;
  season?: string;
  period?: string;
  watermark?: string;
}

const SIGNATURE_PATH = path.resolve(
  __dirname,
  "..",
  "..",
  "public",
  "signature.png",
);

export class ReportBrandingService {
  private readonly LOGO_PATH = path.resolve(
    __dirname,
    "..",
    "..",
    "public",
    "imbaraga-logo.png",
  );

  getSignatureBase64(): string {
    try {
      if (fs.existsSync(SIGNATURE_PATH)) {
        const sigBuffer = fs.readFileSync(SIGNATURE_PATH);
        return `data:image/png;base64,${sigBuffer.toString("base64")}`;
      }
      return "";
    } catch (error) {
      return "";
    }
  }

  getLogoBase64(): string {
    try {
      if (fs.existsSync(this.LOGO_PATH)) {
        const logoBuffer = fs.readFileSync(this.LOGO_PATH);
        return `data:image/png;base64,${logoBuffer.toString("base64")}`;
      }
      return "";
    } catch (error) {
      return "";
    }
  }

  getLogoPath(): string {
    return this.LOGO_PATH;
  }

  // Helper: Format date to "04 Jun 2026, 13:12 UTC"
  formatDate(isoString: string | Date): string {
    if (!isoString) return "N/A";
    const date =
      typeof isoString === "string" ? new Date(isoString) : isoString;
    const months = [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ];
    const d = date.getUTCDate();
    const m = months[date.getUTCMonth()];
    const y = date.getUTCFullYear();
    const h = String(date.getUTCHours()).padStart(2, "0");
    const min = String(date.getUTCMinutes()).padStart(2, "0");
    return `${String(d).padStart(2, "0")} ${m} ${y}, ${h}:${min} UTC`;
  }

  // Helper: Truncate long strings
  truncate(str: string, max: number): string {
    if (!str) return "";
    if (str.length <= max) return str;
    return str.substring(0, max - 1) + "…";
  }

  // Helper: Status badge builder
  statusBadge(status: string): string {
    const s = status.toLowerCase();
    let bg = "#f3f4f6";
    let text = "#374151";

    if (
      s.includes("success") ||
      s.includes("complete") ||
      s.includes("pass") ||
      s.includes("active")
    ) {
      bg = "#dcfce7";
      text = "#166534";
    } else if (
      s.includes("fail") ||
      s.includes("error") ||
      s.includes("block") ||
      s.includes("inactive")
    ) {
      bg = "#fee2e2";
      text = "#991b1b";
    } else if (
      s.includes("pending") ||
      s.includes("process") ||
      s.includes("warn")
    ) {
      bg = "#fef3c7";
      text = "#92400e";
    }

    return `<span style="background: ${bg}; color: ${text}; border-radius: 999px; padding: 2px 10px; font-size: 11px; font-weight: 500; display: inline-block; text-transform: uppercase;">${status}</span>`;
  }

  getPDFHeaderTemplate(meta: BrandingMetadata): string {
    const logoBase64 = this.getLogoBase64();
    const formattedDate = this.formatDate(meta.generatedAt);

    return `
      <div style="width: 100%; font-family: system-ui, -apple-system, sans-serif; padding: 20px 40px; border-bottom: 2px solid #1D9E75; background: white; -webkit-print-color-adjust: exact; display: flex; justify-content: space-between; align-items: flex-start;">
        <div style="display: flex; gap: 15px; align-items: center;">
          <img src="${logoBase64}" style="height: 50px; width: auto;" />
          <div>
            <div style="font-weight: 800; font-size: 16px; color: #1D9E75; letter-spacing: -0.02em;">AGUKA SMART FARMING KIT</div>
            <div style="font-size: 10px; color: #6b7280; font-weight: 500;">Smart Agriculture Monitoring & Decision Support System</div>
            <div style="font-size: 14px; font-weight: 600; color: #1f2937; margin-top: 4px; text-transform: uppercase;">${meta.reportTitle}</div>
          </div>
        </div>
        <div style="text-align: right; font-size: 10px; color: #6b7280; line-height: 1.4;">
          <div style="font-weight: bold; color: #374151;">Generated By: <span style="font-weight: normal;">${meta.generatedBy || "System"}</span></div>
          <div>Role: ${meta.userRole || "N/A"}</div>
          <div>Date: ${formattedDate}</div>
          ${meta.season ? `<div style="color: #1D9E75; font-weight: bold; margin-top: 2px;">${meta.season}</div>` : ""}
        </div>
      </div>
    `;
  }

  getPDFFooterTemplate(): string {
    return `
      <div style="width: 100%; font-family: system-ui, -apple-system, sans-serif; padding: 15px 40px; border-top: 1px solid rgba(29, 158, 117, 0.4); background: white; -webkit-print-color-adjust: exact; display: flex; justify-content: space-between; align-items: center; font-size: 10px; color: #9ca3af;">
        <div>Generated by AGUKA SMART FARMING KIT | <span style="font-style: italic;">Confidential Report</span></div>
        <div style="font-weight: 600; color: #4b5563;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>
      </div>
    `;
  }

  getWatermarkCSS(): string {
    return `
      .watermark {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(-45deg);
        font-size: 80px;
        font-weight: 900;
        color: rgba(29, 158, 117, 0.03);
        pointer-events: none;
        z-index: -1;
        white-space: nowrap;
        font-family: system-ui, sans-serif;
        text-transform: uppercase;
      }
    `;
  }
}

export const reportBrandingService = new ReportBrandingService();
