/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CooperativeRouteImport } from './routes/cooperative'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as CooperativeIndexRouteImport } from './routes/cooperative.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminRolesRouteImport } from './routes/super-admin.roles'
import { Route as SuperAdminHealthRouteImport } from './routes/super-admin.health'
import { Route as SuperAdminBackupsRouteImport } from './routes/super-admin.backups'
import { Route as SuperAdminAuditRouteImport } from './routes/super-admin.audit'
import { Route as ReportsWeatherRouteImport } from './routes/reports.weather'
import { Route as ReportsSoilRouteImport } from './routes/reports.soil'
import { Route as ReportsIrrigationRouteImport } from './routes/reports.irrigation'
import { Route as ReportsActivitiesRouteImport } from './routes/reports.activities'
import { Route as OfficerRisksRouteImport } from './routes/officer.risks'
import { Route as OfficerReportsRouteImport } from './routes/officer.reports'
import { Route as OfficerPestDiseaseRouteImport } from './routes/officer.pest-disease'
import { Route as OfficerFarmsRouteImport } from './routes/officer.farms'
import { Route as OfficerAnalysisRouteImport } from './routes/officer/analysis'
import { Route as OfficerAdvisoriesRouteImport } from './routes/officer.advisories'
import { Route as ForgotPasswordVerifyRouteImport } from './routes/forgot-password.verify'
import { Route as ForgotPasswordSupportRouteImport } from './routes/forgot-password.support'
import { Route as ForgotPasswordResetRouteImport } from './routes/forgot-password.reset'
import { Route as FarmerWeatherRouteImport } from './routes/farmer.weather'
import { Route as FarmerSoilRouteImport } from './routes/farmer.soil'
import { Route as FarmerRecommendationsRouteImport } from './routes/farmer/recommendations'
import { Route as FarmerProfileRouteImport } from './routes/farmer.profile'
import { Route as FarmerNotificationsRouteImport } from './routes/farmer.notifications'
import { Route as FarmerMarketRouteImport } from './routes/farmer.market'
import { Route as FarmerIrrigationRouteImport } from './routes/farmer.irrigation'
import { Route as FarmerGuidanceRouteImport } from './routes/farmer.guidance'
import { Route as FarmerCropsRouteImport } from './routes/farmer.crops'
import { Route as FarmerCommunityRouteImport } from './routes/farmer.community'
import { Route as FarmerAiRouteImport } from './routes/farmer.ai'
import { Route as FarmerActivitiesRouteImport } from './routes/farmer.activities'
import { Route as CooperativeResourcesRouteImport } from './routes/cooperative.resources'
import { Route as CooperativeReportsRouteImport } from './routes/cooperative.reports'
import { Route as CooperativePerformanceRouteImport } from './routes/cooperative.performance'
import { Route as CooperativeFarmersRouteImport } from './routes/cooperative.farmers'
import { Route as CooperativeEventsRouteImport } from './routes/cooperative.events'
import { Route as CooperativeAiRouteImport } from './routes/cooperative.ai'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminFarmsRouteImport } from './routes/admin.farms'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CooperativeRoute = CooperativeRouteImport.update({
  id: '/cooperative',
  path: '/cooperative',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const CooperativeIndexRoute = CooperativeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CooperativeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminRolesRoute = SuperAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminHealthRoute = SuperAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBackupsRoute = SuperAdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAuditRoute = SuperAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ReportsWeatherRoute = ReportsWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSoilRoute = ReportsSoilRouteImport.update({
  id: '/soil',
  path: '/soil',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsIrrigationRoute = ReportsIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsActivitiesRoute = ReportsActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => ReportsRoute,
} as any)
const OfficerRisksRoute = OfficerRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerReportsRoute = OfficerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerPestDiseaseRoute = OfficerPestDiseaseRouteImport.update({
  id: '/pest-disease',
  path: '/pest-disease',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerFarmsRoute = OfficerFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerAnalysisRoute = OfficerAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerAdvisoriesRoute = OfficerAdvisoriesRouteImport.update({
  id: '/advisories',
  path: '/advisories',
  getParentRoute: () => OfficerRoute,
} as any)
const ForgotPasswordVerifyRoute = ForgotPasswordVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ForgotPasswordRoute,
} as any)
const ForgotPasswordSupportRoute = ForgotPasswordSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ForgotPasswordRoute,
} as any)
const ForgotPasswordResetRoute = ForgotPasswordResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => ForgotPasswordRoute,
} as any)
const FarmerWeatherRoute = FarmerWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerSoilRoute = FarmerSoilRouteImport.update({
  id: '/soil',
  path: '/soil',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerRecommendationsRoute = FarmerRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerNotificationsRoute = FarmerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerMarketRoute = FarmerMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerIrrigationRoute = FarmerIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerGuidanceRoute = FarmerGuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerCropsRoute = FarmerCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerCommunityRoute = FarmerCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAiRoute = FarmerAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerActivitiesRoute = FarmerActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => FarmerRoute,
} as any)
const CooperativeResourcesRoute = CooperativeResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => CooperativeRoute,
} as any)
const CooperativeReportsRoute = CooperativeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CooperativeRoute,
} as any)
const CooperativePerformanceRoute = CooperativePerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => CooperativeRoute,
} as any)
const CooperativeFarmersRoute = CooperativeFarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => CooperativeRoute,
} as any)
const CooperativeEventsRoute = CooperativeEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CooperativeRoute,
} as any)
const CooperativeAiRoute = CooperativeAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => CooperativeRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFarmsRoute = AdminFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/cooperative': typeof CooperativeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/farms': typeof AdminFarmsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cooperative/ai': typeof CooperativeAiRoute
  '/cooperative/events': typeof CooperativeEventsRoute
  '/cooperative/farmers': typeof CooperativeFarmersRoute
  '/cooperative/performance': typeof CooperativePerformanceRoute
  '/cooperative/reports': typeof CooperativeReportsRoute
  '/cooperative/resources': typeof CooperativeResourcesRoute
  '/farmer/activities': typeof FarmerActivitiesRoute
  '/farmer/ai': typeof FarmerAiRoute
  '/farmer/community': typeof FarmerCommunityRoute
  '/farmer/crops': typeof FarmerCropsRoute
  '/farmer/guidance': typeof FarmerGuidanceRoute
  '/farmer/irrigation': typeof FarmerIrrigationRoute
  '/farmer/market': typeof FarmerMarketRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/recommendations': typeof FarmerRecommendationsRoute
  '/farmer/soil': typeof FarmerSoilRoute
  '/farmer/weather': typeof FarmerWeatherRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/support': typeof ForgotPasswordSupportRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/officer/advisories': typeof OfficerAdvisoriesRoute
  '/officer/analysis': typeof OfficerAnalysisRoute
  '/officer/farms': typeof OfficerFarmsRoute
  '/officer/pest-disease': typeof OfficerPestDiseaseRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/risks': typeof OfficerRisksRoute
  '/reports/activities': typeof ReportsActivitiesRoute
  '/reports/irrigation': typeof ReportsIrrigationRoute
  '/reports/soil': typeof ReportsSoilRoute
  '/reports/weather': typeof ReportsWeatherRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/backups': typeof SuperAdminBackupsRoute
  '/super-admin/health': typeof SuperAdminHealthRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/cooperative/': typeof CooperativeIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/admin/farms': typeof AdminFarmsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cooperative/ai': typeof CooperativeAiRoute
  '/cooperative/events': typeof CooperativeEventsRoute
  '/cooperative/farmers': typeof CooperativeFarmersRoute
  '/cooperative/performance': typeof CooperativePerformanceRoute
  '/cooperative/reports': typeof CooperativeReportsRoute
  '/cooperative/resources': typeof CooperativeResourcesRoute
  '/farmer/activities': typeof FarmerActivitiesRoute
  '/farmer/ai': typeof FarmerAiRoute
  '/farmer/community': typeof FarmerCommunityRoute
  '/farmer/crops': typeof FarmerCropsRoute
  '/farmer/guidance': typeof FarmerGuidanceRoute
  '/farmer/irrigation': typeof FarmerIrrigationRoute
  '/farmer/market': typeof FarmerMarketRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/recommendations': typeof FarmerRecommendationsRoute
  '/farmer/soil': typeof FarmerSoilRoute
  '/farmer/weather': typeof FarmerWeatherRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/support': typeof ForgotPasswordSupportRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/officer/advisories': typeof OfficerAdvisoriesRoute
  '/officer/analysis': typeof OfficerAnalysisRoute
  '/officer/farms': typeof OfficerFarmsRoute
  '/officer/pest-disease': typeof OfficerPestDiseaseRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/risks': typeof OfficerRisksRoute
  '/reports/activities': typeof ReportsActivitiesRoute
  '/reports/irrigation': typeof ReportsIrrigationRoute
  '/reports/soil': typeof ReportsSoilRoute
  '/reports/weather': typeof ReportsWeatherRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/backups': typeof SuperAdminBackupsRoute
  '/super-admin/health': typeof SuperAdminHealthRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/cooperative': typeof CooperativeIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/cooperative': typeof CooperativeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/farms': typeof AdminFarmsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cooperative/ai': typeof CooperativeAiRoute
  '/cooperative/events': typeof CooperativeEventsRoute
  '/cooperative/farmers': typeof CooperativeFarmersRoute
  '/cooperative/performance': typeof CooperativePerformanceRoute
  '/cooperative/reports': typeof CooperativeReportsRoute
  '/cooperative/resources': typeof CooperativeResourcesRoute
  '/farmer/activities': typeof FarmerActivitiesRoute
  '/farmer/ai': typeof FarmerAiRoute
  '/farmer/community': typeof FarmerCommunityRoute
  '/farmer/crops': typeof FarmerCropsRoute
  '/farmer/guidance': typeof FarmerGuidanceRoute
  '/farmer/irrigation': typeof FarmerIrrigationRoute
  '/farmer/market': typeof FarmerMarketRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/recommendations': typeof FarmerRecommendationsRoute
  '/farmer/soil': typeof FarmerSoilRoute
  '/farmer/weather': typeof FarmerWeatherRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/support': typeof ForgotPasswordSupportRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/officer/advisories': typeof OfficerAdvisoriesRoute
  '/officer/analysis': typeof OfficerAnalysisRoute
  '/officer/farms': typeof OfficerFarmsRoute
  '/officer/pest-disease': typeof OfficerPestDiseaseRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/risks': typeof OfficerRisksRoute
  '/reports/activities': typeof ReportsActivitiesRoute
  '/reports/irrigation': typeof ReportsIrrigationRoute
  '/reports/soil': typeof ReportsSoilRoute
  '/reports/weather': typeof ReportsWeatherRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/backups': typeof SuperAdminBackupsRoute
  '/super-admin/health': typeof SuperAdminHealthRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/cooperative/': typeof CooperativeIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/cooperative'
    | '/dashboard'
    | '/farmer'
    | '/forgot-password'
    | '/officer'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/super-admin'
    | '/terms'
    | '/admin/farms'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/cooperative/ai'
    | '/cooperative/events'
    | '/cooperative/farmers'
    | '/cooperative/performance'
    | '/cooperative/reports'
    | '/cooperative/resources'
    | '/farmer/activities'
    | '/farmer/ai'
    | '/farmer/community'
    | '/farmer/crops'
    | '/farmer/guidance'
    | '/farmer/irrigation'
    | '/farmer/market'
    | '/farmer/notifications'
    | '/farmer/profile'
    | '/farmer/recommendations'
    | '/farmer/soil'
    | '/farmer/weather'
    | '/forgot-password/reset'
    | '/forgot-password/support'
    | '/forgot-password/verify'
    | '/officer/advisories'
    | '/officer/analysis'
    | '/officer/farms'
    | '/officer/pest-disease'
    | '/officer/reports'
    | '/officer/risks'
    | '/reports/activities'
    | '/reports/irrigation'
    | '/reports/soil'
    | '/reports/weather'
    | '/super-admin/audit'
    | '/super-admin/backups'
    | '/super-admin/health'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/admin/'
    | '/cooperative/'
    | '/farmer/'
    | '/officer/'
    | '/reports/'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/onboarding'
    | '/profile'
    | '/terms'
    | '/admin/farms'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/cooperative/ai'
    | '/cooperative/events'
    | '/cooperative/farmers'
    | '/cooperative/performance'
    | '/cooperative/reports'
    | '/cooperative/resources'
    | '/farmer/activities'
    | '/farmer/ai'
    | '/farmer/community'
    | '/farmer/crops'
    | '/farmer/guidance'
    | '/farmer/irrigation'
    | '/farmer/market'
    | '/farmer/notifications'
    | '/farmer/profile'
    | '/farmer/recommendations'
    | '/farmer/soil'
    | '/farmer/weather'
    | '/forgot-password/reset'
    | '/forgot-password/support'
    | '/forgot-password/verify'
    | '/officer/advisories'
    | '/officer/analysis'
    | '/officer/farms'
    | '/officer/pest-disease'
    | '/officer/reports'
    | '/officer/risks'
    | '/reports/activities'
    | '/reports/irrigation'
    | '/reports/soil'
    | '/reports/weather'
    | '/super-admin/audit'
    | '/super-admin/backups'
    | '/super-admin/health'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/admin'
    | '/cooperative'
    | '/farmer'
    | '/officer'
    | '/reports'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/cooperative'
    | '/dashboard'
    | '/farmer'
    | '/forgot-password'
    | '/officer'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/super-admin'
    | '/terms'
    | '/admin/farms'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/cooperative/ai'
    | '/cooperative/events'
    | '/cooperative/farmers'
    | '/cooperative/performance'
    | '/cooperative/reports'
    | '/cooperative/resources'
    | '/farmer/activities'
    | '/farmer/ai'
    | '/farmer/community'
    | '/farmer/crops'
    | '/farmer/guidance'
    | '/farmer/irrigation'
    | '/farmer/market'
    | '/farmer/notifications'
    | '/farmer/profile'
    | '/farmer/recommendations'
    | '/farmer/soil'
    | '/farmer/weather'
    | '/forgot-password/reset'
    | '/forgot-password/support'
    | '/forgot-password/verify'
    | '/officer/advisories'
    | '/officer/analysis'
    | '/officer/farms'
    | '/officer/pest-disease'
    | '/officer/reports'
    | '/officer/risks'
    | '/reports/activities'
    | '/reports/irrigation'
    | '/reports/soil'
    | '/reports/weather'
    | '/super-admin/audit'
    | '/super-admin/backups'
    | '/super-admin/health'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/admin/'
    | '/cooperative/'
    | '/farmer/'
    | '/officer/'
    | '/reports/'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CooperativeRoute: typeof CooperativeRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRouteWithChildren
  OfficerRoute: typeof OfficerRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooperative': {
      id: '/cooperative'
      path: '/cooperative'
      fullPath: '/cooperative'
      preLoaderRoute: typeof CooperativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/cooperative/': {
      id: '/cooperative/'
      path: '/'
      fullPath: '/cooperative/'
      preLoaderRoute: typeof CooperativeIndexRouteImport
      parentRoute: typeof CooperativeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/roles': {
      id: '/super-admin/roles'
      path: '/roles'
      fullPath: '/super-admin/roles'
      preLoaderRoute: typeof SuperAdminRolesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/health': {
      id: '/super-admin/health'
      path: '/health'
      fullPath: '/super-admin/health'
      preLoaderRoute: typeof SuperAdminHealthRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/backups': {
      id: '/super-admin/backups'
      path: '/backups'
      fullPath: '/super-admin/backups'
      preLoaderRoute: typeof SuperAdminBackupsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/audit': {
      id: '/super-admin/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof SuperAdminAuditRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/reports/weather': {
      id: '/reports/weather'
      path: '/weather'
      fullPath: '/reports/weather'
      preLoaderRoute: typeof ReportsWeatherRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/soil': {
      id: '/reports/soil'
      path: '/soil'
      fullPath: '/reports/soil'
      preLoaderRoute: typeof ReportsSoilRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/irrigation': {
      id: '/reports/irrigation'
      path: '/irrigation'
      fullPath: '/reports/irrigation'
      preLoaderRoute: typeof ReportsIrrigationRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/activities': {
      id: '/reports/activities'
      path: '/activities'
      fullPath: '/reports/activities'
      preLoaderRoute: typeof ReportsActivitiesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/officer/risks': {
      id: '/officer/risks'
      path: '/risks'
      fullPath: '/officer/risks'
      preLoaderRoute: typeof OfficerRisksRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/reports': {
      id: '/officer/reports'
      path: '/reports'
      fullPath: '/officer/reports'
      preLoaderRoute: typeof OfficerReportsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/pest-disease': {
      id: '/officer/pest-disease'
      path: '/pest-disease'
      fullPath: '/officer/pest-disease'
      preLoaderRoute: typeof OfficerPestDiseaseRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/farms': {
      id: '/officer/farms'
      path: '/farms'
      fullPath: '/officer/farms'
      preLoaderRoute: typeof OfficerFarmsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/analysis': {
      id: '/officer/analysis'
      path: '/analysis'
      fullPath: '/officer/analysis'
      preLoaderRoute: typeof OfficerAnalysisRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/advisories': {
      id: '/officer/advisories'
      path: '/advisories'
      fullPath: '/officer/advisories'
      preLoaderRoute: typeof OfficerAdvisoriesRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/forgot-password/verify': {
      id: '/forgot-password/verify'
      path: '/verify'
      fullPath: '/forgot-password/verify'
      preLoaderRoute: typeof ForgotPasswordVerifyRouteImport
      parentRoute: typeof ForgotPasswordRoute
    }
    '/forgot-password/support': {
      id: '/forgot-password/support'
      path: '/support'
      fullPath: '/forgot-password/support'
      preLoaderRoute: typeof ForgotPasswordSupportRouteImport
      parentRoute: typeof ForgotPasswordRoute
    }
    '/forgot-password/reset': {
      id: '/forgot-password/reset'
      path: '/reset'
      fullPath: '/forgot-password/reset'
      preLoaderRoute: typeof ForgotPasswordResetRouteImport
      parentRoute: typeof ForgotPasswordRoute
    }
    '/farmer/weather': {
      id: '/farmer/weather'
      path: '/weather'
      fullPath: '/farmer/weather'
      preLoaderRoute: typeof FarmerWeatherRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/soil': {
      id: '/farmer/soil'
      path: '/soil'
      fullPath: '/farmer/soil'
      preLoaderRoute: typeof FarmerSoilRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/recommendations': {
      id: '/farmer/recommendations'
      path: '/recommendations'
      fullPath: '/farmer/recommendations'
      preLoaderRoute: typeof FarmerRecommendationsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/profile': {
      id: '/farmer/profile'
      path: '/profile'
      fullPath: '/farmer/profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/notifications': {
      id: '/farmer/notifications'
      path: '/notifications'
      fullPath: '/farmer/notifications'
      preLoaderRoute: typeof FarmerNotificationsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/market': {
      id: '/farmer/market'
      path: '/market'
      fullPath: '/farmer/market'
      preLoaderRoute: typeof FarmerMarketRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/irrigation': {
      id: '/farmer/irrigation'
      path: '/irrigation'
      fullPath: '/farmer/irrigation'
      preLoaderRoute: typeof FarmerIrrigationRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/guidance': {
      id: '/farmer/guidance'
      path: '/guidance'
      fullPath: '/farmer/guidance'
      preLoaderRoute: typeof FarmerGuidanceRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/crops': {
      id: '/farmer/crops'
      path: '/crops'
      fullPath: '/farmer/crops'
      preLoaderRoute: typeof FarmerCropsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/community': {
      id: '/farmer/community'
      path: '/community'
      fullPath: '/farmer/community'
      preLoaderRoute: typeof FarmerCommunityRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/ai': {
      id: '/farmer/ai'
      path: '/ai'
      fullPath: '/farmer/ai'
      preLoaderRoute: typeof FarmerAiRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/activities': {
      id: '/farmer/activities'
      path: '/activities'
      fullPath: '/farmer/activities'
      preLoaderRoute: typeof FarmerActivitiesRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/cooperative/resources': {
      id: '/cooperative/resources'
      path: '/resources'
      fullPath: '/cooperative/resources'
      preLoaderRoute: typeof CooperativeResourcesRouteImport
      parentRoute: typeof CooperativeRoute
    }
    '/cooperative/reports': {
      id: '/cooperative/reports'
      path: '/reports'
      fullPath: '/cooperative/reports'
      preLoaderRoute: typeof CooperativeReportsRouteImport
      parentRoute: typeof CooperativeRoute
    }
    '/cooperative/performance': {
      id: '/cooperative/performance'
      path: '/performance'
      fullPath: '/cooperative/performance'
      preLoaderRoute: typeof CooperativePerformanceRouteImport
      parentRoute: typeof CooperativeRoute
    }
    '/cooperative/farmers': {
      id: '/cooperative/farmers'
      path: '/farmers'
      fullPath: '/cooperative/farmers'
      preLoaderRoute: typeof CooperativeFarmersRouteImport
      parentRoute: typeof CooperativeRoute
    }
    '/cooperative/events': {
      id: '/cooperative/events'
      path: '/events'
      fullPath: '/cooperative/events'
      preLoaderRoute: typeof CooperativeEventsRouteImport
      parentRoute: typeof CooperativeRoute
    }
    '/cooperative/ai': {
      id: '/cooperative/ai'
      path: '/ai'
      fullPath: '/cooperative/ai'
      preLoaderRoute: typeof CooperativeAiRouteImport
      parentRoute: typeof CooperativeRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/farms': {
      id: '/admin/farms'
      path: '/farms'
      fullPath: '/admin/farms'
      preLoaderRoute: typeof AdminFarmsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFarmsRoute: typeof AdminFarmsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFarmsRoute: AdminFarmsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CooperativeRouteChildren {
  CooperativeAiRoute: typeof CooperativeAiRoute
  CooperativeEventsRoute: typeof CooperativeEventsRoute
  CooperativeFarmersRoute: typeof CooperativeFarmersRoute
  CooperativePerformanceRoute: typeof CooperativePerformanceRoute
  CooperativeReportsRoute: typeof CooperativeReportsRoute
  CooperativeResourcesRoute: typeof CooperativeResourcesRoute
  CooperativeIndexRoute: typeof CooperativeIndexRoute
}

const CooperativeRouteChildren: CooperativeRouteChildren = {
  CooperativeAiRoute: CooperativeAiRoute,
  CooperativeEventsRoute: CooperativeEventsRoute,
  CooperativeFarmersRoute: CooperativeFarmersRoute,
  CooperativePerformanceRoute: CooperativePerformanceRoute,
  CooperativeReportsRoute: CooperativeReportsRoute,
  CooperativeResourcesRoute: CooperativeResourcesRoute,
  CooperativeIndexRoute: CooperativeIndexRoute,
}

const CooperativeRouteWithChildren = CooperativeRoute._addFileChildren(
  CooperativeRouteChildren,
)

interface FarmerRouteChildren {
  FarmerActivitiesRoute: typeof FarmerActivitiesRoute
  FarmerAiRoute: typeof FarmerAiRoute
  FarmerCommunityRoute: typeof FarmerCommunityRoute
  FarmerCropsRoute: typeof FarmerCropsRoute
  FarmerGuidanceRoute: typeof FarmerGuidanceRoute
  FarmerIrrigationRoute: typeof FarmerIrrigationRoute
  FarmerMarketRoute: typeof FarmerMarketRoute
  FarmerNotificationsRoute: typeof FarmerNotificationsRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  FarmerRecommendationsRoute: typeof FarmerRecommendationsRoute
  FarmerSoilRoute: typeof FarmerSoilRoute
  FarmerWeatherRoute: typeof FarmerWeatherRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerActivitiesRoute: FarmerActivitiesRoute,
  FarmerAiRoute: FarmerAiRoute,
  FarmerCommunityRoute: FarmerCommunityRoute,
  FarmerCropsRoute: FarmerCropsRoute,
  FarmerGuidanceRoute: FarmerGuidanceRoute,
  FarmerIrrigationRoute: FarmerIrrigationRoute,
  FarmerMarketRoute: FarmerMarketRoute,
  FarmerNotificationsRoute: FarmerNotificationsRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  FarmerRecommendationsRoute: FarmerRecommendationsRoute,
  FarmerSoilRoute: FarmerSoilRoute,
  FarmerWeatherRoute: FarmerWeatherRoute,
  FarmerIndexRoute: FarmerIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface ForgotPasswordRouteChildren {
  ForgotPasswordResetRoute: typeof ForgotPasswordResetRoute
  ForgotPasswordSupportRoute: typeof ForgotPasswordSupportRoute
  ForgotPasswordVerifyRoute: typeof ForgotPasswordVerifyRoute
}

const ForgotPasswordRouteChildren: ForgotPasswordRouteChildren = {
  ForgotPasswordResetRoute: ForgotPasswordResetRoute,
  ForgotPasswordSupportRoute: ForgotPasswordSupportRoute,
  ForgotPasswordVerifyRoute: ForgotPasswordVerifyRoute,
}

const ForgotPasswordRouteWithChildren = ForgotPasswordRoute._addFileChildren(
  ForgotPasswordRouteChildren,
)

interface OfficerRouteChildren {
  OfficerAdvisoriesRoute: typeof OfficerAdvisoriesRoute
  OfficerAnalysisRoute: typeof OfficerAnalysisRoute
  OfficerFarmsRoute: typeof OfficerFarmsRoute
  OfficerPestDiseaseRoute: typeof OfficerPestDiseaseRoute
  OfficerReportsRoute: typeof OfficerReportsRoute
  OfficerRisksRoute: typeof OfficerRisksRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerAdvisoriesRoute: OfficerAdvisoriesRoute,
  OfficerAnalysisRoute: OfficerAnalysisRoute,
  OfficerFarmsRoute: OfficerFarmsRoute,
  OfficerPestDiseaseRoute: OfficerPestDiseaseRoute,
  OfficerReportsRoute: OfficerReportsRoute,
  OfficerRisksRoute: OfficerRisksRoute,
  OfficerIndexRoute: OfficerIndexRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

interface ReportsRouteChildren {
  ReportsActivitiesRoute: typeof ReportsActivitiesRoute
  ReportsIrrigationRoute: typeof ReportsIrrigationRoute
  ReportsSoilRoute: typeof ReportsSoilRoute
  ReportsWeatherRoute: typeof ReportsWeatherRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsActivitiesRoute: ReportsActivitiesRoute,
  ReportsIrrigationRoute: ReportsIrrigationRoute,
  ReportsSoilRoute: ReportsSoilRoute,
  ReportsWeatherRoute: ReportsWeatherRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminAuditRoute: typeof SuperAdminAuditRoute
  SuperAdminBackupsRoute: typeof SuperAdminBackupsRoute
  SuperAdminHealthRoute: typeof SuperAdminHealthRoute
  SuperAdminRolesRoute: typeof SuperAdminRolesRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAuditRoute: SuperAdminAuditRoute,
  SuperAdminBackupsRoute: SuperAdminBackupsRoute,
  SuperAdminHealthRoute: SuperAdminHealthRoute,
  SuperAdminRolesRoute: SuperAdminRolesRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CooperativeRoute: CooperativeRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FarmerRoute: FarmerRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRouteWithChildren,
  OfficerRoute: OfficerRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
